### ISSUE TITLE
Compatibility with HHVM

### ISSUE THREAD

**Issue by lisachenko** [goaop/framework#143]
Issue to track compatibility issues with HHVM
- [x] https://github.com/lisachenko/go-aop-php/issues/144 [HHVM] constructor for php_user_filter requires three internal parameters
- [x] https://github.com/lisachenko/go-aop-php/issues/145 [HHVM] add HHVM to matrix for travis-ci
- [x] https://github.com/lisachenko/go-aop-php/issues/146 [HHVM] use nightly builds for testing
- [x] https://github.com/facebook/hhvm/issues/1241 Zend incompatibility: unknown class php_user_filter
- [x] https://github.com/facebook/hhvm/issues/1242 ReflectionMethod->getClosure() is not working
- [x] https://github.com/facebook/hhvm/issues/1353 Behavior diff: ReflectionMethod::getClosure() does not work
- [x] https://github.com/facebook/hhvm/issues/1203 Support for Closure::bind is missing
- [x] https://github.com/facebook/hhvm/issues/2485 HHVM can not find a file with php://filter
- https://github.com/facebook/hhvm/issues/2486 Incorrect scope handling in ReflectionMethod **Not needed anymore.**
- [x] https://github.com/facebook/hhvm/issues/2493 Undefined property: ReflectionFunction::$name
- [x] https://github.com/goaop/framework/issues/250 [HHVM] Prepare special getClosure() implementation for HHVM support
- https://github.com/facebook/hhvm/issues/6834 Dynamic includes with stream filters are not working **Not needed anymore. HHVM support was dropped**
- https://github.com/facebook/hhvm/issues/3772 Fatal error: Call to undefined method invokeArgs() after closure rebinding **Not needed anymore. HHVM support was dropped**

**Comment by lisachenko** [comment]
One more issue was fixed with Closure::bind

**Comment by newtonianb** [comment]
@lisachenko, it seems it's not entirely in your control but do you see any roadmap on having HHVM working with go aop anytime soon?

**Comment by lisachenko** [comment]
@newtonianb unfortunately, HHVM engine is not suited for very dynamic things, such as method rebinding. `RepoAuthoriative` mode will never work with aspects, but there is a small chance to make this working under HHVM by defining custom `ReflectionMethod` class with overridden `getClosure()` method, implemented by hand.

**Comment by lisachenko** [comment]
Just tried to define my own version of `ReflectionMethod->getClosure()` and surpassingly, it works now under HHVM. However HHVM still suffers from include with enabled stream filters, but if the cache is prepared, then framework will be running on HHVM :) And this is really fast!

**Comment by lisachenko** [comment]
Following the trend to drop the support of HHVM, I think that I can follow this way, because no visible changes in the HHVM and supporting HHVM isn't killer feature anymore.

See: 

1. https://github.com/doctrine/doctrine2/issues/6424
2. https://github.com/symfony/symfony/issues/18922

and linked issues in these threads
