### ISSUE TITLE
Optimize proxies generation and invocations for PHP versions 5.5 and 5.6

### ISSUE THREAD

**Issue by lisachenko** [goaop/framework#165]
Meta-task to track optimizations for new versions of PHP.
- [x] https://github.com/lisachenko/go-aop-php/issues/166  [Optimization] faster access to the LSB class name
- [x] https://github.com/lisachenko/go-aop-php/issues/167 [Optimization] Create an optimized ClosureDynamicMethodInvocation for PHP>=5.6.0 
- [x] https://github.com/lisachenko/go-aop-php/issues/176  [Optimization] replace sprintf() call with direct string initializaion

Available optimizations:
- Use splat operator with variadic functions for function proxies. Unfortunately, It isn't possible to use variadic definition for methods, because this can violate interfaces or abstract methods. One more issue is that parameters by reference can not be handled with variadics.
- Switch to "use function" instead of defining proxies for system functions in each namespace. This patch will give less memory consumption and more optimized invocation for PHP engine.
- Do not check for the presence of `func_get_args()` in the source code of methods during a proxy generation. This can be solved with variadic method definition, but only after fixing internal PHP bug https://bugs.php.net/bug.php?id=67938

**Comment by lisachenko** [comment]
PHP bug https://bugs.php.net/bug.php?id=67938 is fixed now, so it's possible to use variadics for PHP>=5.6.1
