### ISSUE TITLE
Compatibility with PHP5.6/PHP7

### ISSUE THREAD

**Issue by lisachenko** [goaop/framework#175]
Meta-issue to track current state for PHP>=7.0.0
- [x] #170 [FunctionProxy] Invalid handling of variable number of arguments
- [x] #173 Make PointcutGrammar class compatible with PHP7
- [x] https://github.com/php/php-src/pull/900 Incorrect reflection info for array_multisort()
- [x] #216 Support parameter scalar typehints for PHP7
- [x] #247 Drop support for privileged advices for PHP7.0
- [x] #252 Support variadic methods for classes
- [x] #254 Support return typehints for PHP7

**Comment by lisachenko** [comment]
After closing #252, framework is fully PHP5.6 compatible )

**Comment by lisachenko** [comment]
After #254, framework is fully PHP7.0 compatible )
