### ISSUE TITLE
[Proxy] Add support for the PHP 7.1 features

### ISSUE THREAD

**Issue by lisachenko** [goaop/framework#307]
Need to add PHP7.1 features support to the framework:

- [x] Update `goaop/parser-reflection` to the latest version ~1.2, #308 
- [x] Add support for [nullable parameters and return types](https://wiki.php.net/rfc/nullable_types) in proxies. #309 
- [x] Add support for [`void` return type](https://wiki.php.net/rfc/void_return_type) in proxies. #310

**Comment by lisachenko** [comment]
Master branch now can handle 7.1 source code.
